### ISSUE TITLE
wiki Let's Encrypt Cert Expired

### ISSUE THREAD

**Issue by kbkaiser** [void-linux/void-wiki#2]
Not After
5/9/2020, 1:03:20 PM (Eastern Daylight Time)

**Comment by Vaelatern** [comment]
The wiki is depreciated. Use https://docs.voidlinux.org instead.

**Comment by hippi777** [comment]
hi there! :)

i still have a few remaining pages opened from it to read them for making my installer... is there a way to access the contents? i came to this repo in the hope that i will find the contents, but i think they arent available anywhere, while the active work on the docs could benefit from consulting with the wiki pages as well... i believe a lock would be the best, but ive only seen the surface of any wiki, so i dunno if thats a simple possibility or requires hacking... i think the best would be to delete pages that has nothing important remaining related to the existing(/wip) docs. for exampe i think the post install page had much valuable pointers (iirc), while the post install section of the docs just got some complaints about being nearly meaningless...

thx 4 any help! :)

**Comment by Vaelatern** [comment]
@void-linux/doc-writers input? Were we quite ready to retire the wiki?

**Comment by the-maldridge** [comment]
The wiki is deprecated specifically because it is such a pain to maintain and its content is locked up in a database.  You should be able to click past the security warning and still get to it.  I'll see about renewing that cert later today, but I make no promises.

**Comment by hippi777** [comment]
lol, i wanted to check out if i can surpass the warning (that i have already tried, but whatever) and voila, now its just simply accessible without any difficulties :D 

btw i think the best would be to delete it page-by-page, i dont believe that anybody around knows it by heart, and side-by-side with the docs, so, imho, this would be the safe path...

**Comment by the-maldridge** [comment]
I'd like to just convert it to an ePub and then host that somewhere.
The wiki is running on a machine that I need to reclaim.

**Comment by hippi777** [comment]
just as fine! :)

**Comment by hippi777** [comment]
however if it can be any plaintext, then hosting itside the docs repo would let ppl to delete pieces via commits alongside the new docs, or maybe with pointers to existing ones

**Comment by flexibeast** [comment]
@Vaelatern:

Personally, i'd like the wiki to be taken offline as soon as possible - while it's still online, people are continuing to referring others to it in preference to the Handbook, despite the deprecation notice, despite the fact that myself and others been letting people know it's deprecated for over six months now (on r/voidlinux and IRC), and despite the fact that we've been letting people know it contains out-of-date and incorrect information. However, i'm not sure we're there yet, as the Handbook still doesn't include e.g. all the sort of information listed in the wiki's "[Installation](https://wiki.voidlinux.org/Category:Installation)" category, such as installing on a Raspberry Pi or Beaglebone - but such pages would need to be reviewed by someone with physical access to such devices. i guess the question is whether the Void team in general considers things like this to be blockers?

A guide to chroot installation is being put together in https://github.com/void-linux/void-docs/pull/177, and once that's finalised, @ericonr can begin working on pages that can leverage that page (i.e. #177 is a blocker for that work to begin).

@the-maldridge:

Further to @hippi777's suggestion, can we just [dump the wiki to XML](https://www.mediawiki.org/wiki/Help:Export), so we can store the output in the `void-docs` repo for reference, without contributors to the docs needing to use archive.org? Is there a reason you'd prefer to export the database contents to an ePub instead?

**Comment by kbkaiser** [comment]
Cert renewed May 10.  Closing this issue, thanks.

Note that I think I got to the wiki by googling on a specific issue.  I missed the deprecation at the top of the page - it doesn't stand out much.

**Comment by kbkaiser** [comment]
Closing
